Name:           ros-kinetic-cob-utilities
Version:        0.6.10
Release:        0%{?dist}
Summary:        ROS cob_utilities package

Group:          Development/Libraries
License:        LGPL
URL:            http://ros.org/wiki/cob_utilities
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-kinetic-catkin

%description
Deprecated &quot;cob_utilities&quot; subsumes a number of classes, which are
used in the original COb3 software. E.g. &quot;IniFile.h&quot; supports the
original inifile structure of Care-O-bot 3. &quot;MathSup.h&quot; provides some
basic functions like conversion from degree to radion or norming of angles
within +/- PI. The package is currently used while the drivers are ported to ROS
and Orocos respectively. Midterm it shall be removed and the ROS structures
shall be used for reading parameters during initialization. So, don't use this
package in new code!

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Jul 24 2017 Matthias Gruhler <mig@ipa.fhg.de> - 0.6.10-0
- Autogenerated by Bloom

