Name:           ros-kinetic-cob-undercarriage-ctrl
Version:        0.6.10
Release:        0%{?dist}
Summary:        ROS cob_undercarriage_ctrl package

Group:          Development/Libraries
License:        LGPL
URL:            http://ros.org/wiki/cob_undercarriage_ctrl
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-cob-msgs
Requires:       ros-kinetic-cob-utilities
Requires:       ros-kinetic-control-msgs
Requires:       ros-kinetic-diagnostic-msgs
Requires:       ros-kinetic-diagnostic-updater
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-nav-msgs
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-tf
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cob-msgs
BuildRequires:  ros-kinetic-cob-utilities
BuildRequires:  ros-kinetic-control-msgs
BuildRequires:  ros-kinetic-diagnostic-msgs
BuildRequires:  ros-kinetic-diagnostic-updater
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-nav-msgs
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-tf

%description
cob_undercarriage_ctrl implements a controller for the omnidirectional base of
Care-O-bot 3 on joint level. For a given Pltf-Twist the according wheel steering
angles and linear wheel velocities are calculated based on the principle of
rigid body motion. Each joint is than controlled individually to achieve the
computed position and velocity

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Jul 24 2017 Matthias Gruhler <mig@ipa.fhg.de> - 0.6.10-0
- Autogenerated by Bloom

